name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  # local development
  - RISE
  - ipykernel
  - jupyter_contrib_nbextensions
  - notebook
  # should match versions on Colab, from
  # https://github.com/googlecolab/colabtools/blob/master/setup.py
  # or from `!pip show <package>`
  - pandas=1.1.*
  - plotly=4.4.1
  - statsmodels=0.10.2
  # CI
  - nbconvert
  - nbdime
  - pytest
  # other
  - requests
