site_name: Python for Public Policy
# https://github.com/danielfrg/mkdocs-jupyter/issues/14
use_directory_urls: false
plugins:
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Week 0:
      - Lecture: lecture_0.ipynb
      - Homework: hw_0.ipynb
  - Week 1:
      - Lecture: lecture_1.ipynb
      - Homework: hw_1.ipynb
  - Week 2:
      - Lecture: lecture_2.ipynb
      - Homework: hw_2.ipynb
  - Week 3:
      - Lecture: lecture_3.ipynb
      - Homework: hw_3.ipynb
  - Week 4:
      - Lecture: lecture_4.ipynb
      - Homework: hw_4.ipynb
  - Week 5:
      - Lecture: lecture_5.ipynb
      - Exercise: lecture_5_exercise.ipynb
      - Homework: hw_5.ipynb
  - Lecture 6: lecture_6.ipynb

extra_css:
  - css/styles.css
